name: Build Mod

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' 

      - name: Compile Mod
        uses: KSPModdingLibs/KSPBuildTools/.github/actions/compile@main
        with:
          solution-file-path: src/UniversalResourceTransferRedux.sln
          use-nuget-restore: 'false'
