name: Build Mod

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  run-build:
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/build.yml@1.1.1
    with:
      solution-file-path: src/UniversalResourceTransferRedux.sln
      artifacts: 'src/GameData LICENSE* README* CHANGELOG*'
